#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     sensorDist,     sensorSONAR)
#pragma config(Motor,  mtr_Matrix_S1_1, motorE,        tmotorMatrix, openLoop, reversed)
#pragma config(Motor,  mtr_Matrix_S1_2, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorG,        tmotorMatrix, openLoop, reversed)
#pragma config(Motor,  mtr_Matrix_S1_4, motorH,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"

void drive(int powerL, int powerR);
void dump();

task main()
{
	waitForStart();
	bool atIR = false;
	tHTIRS2DSPMode _mode = DSP_1200;
	if (HTIRS2setDSPMode(HTIRS2, _mode) == 0){
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 2.");
		// make a noise to get their attention.
		PlaySound(soundBeepBeep);
	}
	int power = 25;
	int ac[] = {0, 0, 0, 0, 0};
	drive(power, power);
	while(1){
		HTIRS2readAllACStrength(HTIRS2, ac[0], ac[1], ac[2], ac[3], ac[4]);
		for(int i = 1; i < 5; i++){ // try to catch the peak going through the sectors
			writeDebugStream("\ni is %d", i);
			writeDebugStream("\nac[i] - ac[i - 1] is %d", ac[i] - ac[i - 1]);
			if(ac[i] - ac[i - 1] > 120){ // this is just a guess, we need to test this
				power = 0;
				atIR = true;
			/*	if(i > 3) power = -30;
				if(i == 3){
					power = 0;
					atIR = true;
				}
				else{
					power = 0;
					atIR = true;
				}
				*/
			}
			drive(power, power);
		}
		drive(power, power);
		if(atIR){
			wait1Msec(500);
			break;
		}
	}
	dump();
	drive(25, 25);
	wait1Msec(2500);
	drive(25, 10);
	wait1Msec(500);
	drive(25, 25);
	wait1Msec(2500);
	drive(25, 10);
	wait1Msec(500);
	drive(25, 25);
	wait1Msec(2500);
}

void drive(int powerL, int powerR){
	motor[motorE] = -powerL;
	motor[motorG] = powerR;
}
void dump(){
	servo[servo2] = 100;
	wait1Msec(1000);
	servo[servo2] = 0;
}
